//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogDog_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proflie_user
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> district { get; set; }
        public Nullable<int> province { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> date_signin { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> id_user { get; set; }
        public string url_pro_img { get; set; }
        public Nullable<System.DateTime> date_signup { get; set; }
    
        public virtual user user { get; set; }
    }
}
